### ISSUE TITLE
line ending at end of php files

### ISSUE THREAD

**Issue by lorenzop** [WebAuctionPlus/WebAuctionPlus-1.2#2]
extra line ending at the end of php files should be removed. this can possibly cause a problem, as the http headers are sent once php executes down to the bottom of one of the files. after this, things like setting a cookie no longer works.

**Comment by dangerORclose** [comment]
Hey is your webauction webthing working??

**Comment by lorenzop** [comment]
yes, the plugin was working well with minecraft 1.8.x versions, although I haven't looked at it myself in some time. If something has broke, open a new ticket describing the problem and we'll get it fixed.

**Comment by lorenzop** [comment]
the line endings of files, I may have fixed this already. if not, it should probably get done before more work is started.
