### ISSUE TITLE
can't buy / sell

### ISSUE THREAD

**Issue by dangerORclose** [WebAuctionPlus/WebAuctionPlus-1.2#4]
Hello i need help.
I make a servershop.
I add money to my wa account.
Then i log in buy some stuff but when i press buy it guves this eror on the web..

My post i posted on bukkit..
dangerORclose
2 days, 1 hour ago - 0 likes

MySQL ERROR - File: /home/wafmcbe/domains/wafmc.be/public_html/market/inc/classes/servershop.functions.php Line: 311 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id` = 2 LIMIT 1' at line 1

SELECT `qty` FROM WA_ServerShops` WHERE `id` = 2 LIMIT 1

**Comment by lorenzop** [comment]
it looks like there's a back-tick ` character missing in WHERE id`

find the exact version of the jar plugin and reupload the php web files for the same version. that should fix this and any other similar problems.

if you still have this problem after reuploading the web files, update the ticket with the version of web auction you're using and I'll look in the code for the problem, or you can try updating to the latest version of the plugin.
